# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vrs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vrs.proto',
  package='vrs.rpc',
  syntax='proto3',
  serialized_pb=_b('\n\tvrs.proto\x12\x07vrs.rpc\"(\n\x18\x44\x65tectObjectInImgRequest\x12\x0c\n\x04Path\x18\x01 \x01(\t\"\x85\x01\n\x17\x44\x65tectObjectInImgResult\x12\x0f\n\x07\x43lassID\x18\x01 \x01(\r\x12\x11\n\tClassName\x18\x02 \x01(\t\x12\x0c\n\x04Prob\x18\x03 \x01(\x02\x12\x0b\n\x03Top\x18\x04 \x01(\x05\x12\x0c\n\x04Left\x18\x05 \x01(\x05\x12\r\n\x05Width\x18\x06 \x01(\x05\x12\x0e\n\x06Height\x18\x07 \x01(\x05\"(\n\x18\x44\x65tectPersonInImgRequest\x12\x0c\n\x04Path\x18\x01 \x01(\t\"\'\n\x14\x44\x65tectPersonsRequest\x12\x0f\n\x07VideoID\x18\x01 \x01(\r\" \n\rSearchRequest\x12\x0f\n\x07ImgPath\x18\x01 \x01(\t\".\n\x0cSearchResult\x12\r\n\x05Score\x18\x01 \x01(\x02\x12\x0f\n\x07\x46rameID\x18\x02 \x01(\x04\"&\n\x13ProcessVideoRequest\x12\x0f\n\x07VideoID\x18\x01 \x01(\r\"#\n\x06Result\x12\x0c\n\x04\x43ode\x18\x01 \x01(\r\x12\x0b\n\x03Msg\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"e\n\x17\x44\x65tectPersonInImgResult\x12\x10\n\x08PersonID\x18\x01 \x01(\r\x12\x0b\n\x03Top\x18\x02 \x01(\x05\x12\r\n\x05Right\x18\x03 \x01(\x05\x12\x0e\n\x06\x42ottom\x18\x04 \x01(\x05\x12\x0c\n\x04Left\x18\x05 \x01(\x05\x32\xb2\x01\n\x06VrsRpc\x12;\n\x06Search\x12\x16.vrs.rpc.SearchRequest\x1a\x15.vrs.rpc.SearchResult\"\x00\x30\x01\x12?\n\x0cProcessVideo\x12\x1c.vrs.rpc.ProcessVideoRequest\x1a\x0f.vrs.rpc.Result\"\x00\x12*\n\x05Merge\x12\x0e.vrs.rpc.Empty\x1a\x0f.vrs.rpc.Result\"\x00\x32\xe6\x01\n\x07\x46\x61\x63\x65Rpc\x12\x33\n\x0e\x42uildClassifer\x12\x0e.vrs.rpc.Empty\x1a\x0f.vrs.rpc.Result\"\x00\x12H\n\x14\x44\x65tectPersonsInVideo\x12\x1d.vrs.rpc.DetectPersonsRequest\x1a\x0f.vrs.rpc.Result\"\x00\x12\\\n\x11\x44\x65tectPersonInImg\x12!.vrs.rpc.DetectPersonInImgRequest\x1a .vrs.rpc.DetectPersonInImgResult\"\x00\x30\x01\x32i\n\tObjectRpc\x12\\\n\x11\x44\x65tectObjectInImg\x12!.vrs.rpc.DetectObjectInImgRequest\x1a .vrs.rpc.DetectObjectInImgResult\"\x00\x30\x01\x42\x19\n\x15\x65\x64u.gcu.vrs.rpcserverP\x01\x62\x06proto3')
)




_DETECTOBJECTINIMGREQUEST = _descriptor.Descriptor(
  name='DetectObjectInImgRequest',
  full_name='vrs.rpc.DetectObjectInImgRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Path', full_name='vrs.rpc.DetectObjectInImgRequest.Path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=62,
)


_DETECTOBJECTINIMGRESULT = _descriptor.Descriptor(
  name='DetectObjectInImgResult',
  full_name='vrs.rpc.DetectObjectInImgResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ClassID', full_name='vrs.rpc.DetectObjectInImgResult.ClassID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ClassName', full_name='vrs.rpc.DetectObjectInImgResult.ClassName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Prob', full_name='vrs.rpc.DetectObjectInImgResult.Prob', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Top', full_name='vrs.rpc.DetectObjectInImgResult.Top', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Left', full_name='vrs.rpc.DetectObjectInImgResult.Left', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Width', full_name='vrs.rpc.DetectObjectInImgResult.Width', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Height', full_name='vrs.rpc.DetectObjectInImgResult.Height', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=198,
)


_DETECTPERSONINIMGREQUEST = _descriptor.Descriptor(
  name='DetectPersonInImgRequest',
  full_name='vrs.rpc.DetectPersonInImgRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Path', full_name='vrs.rpc.DetectPersonInImgRequest.Path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=240,
)


_DETECTPERSONSREQUEST = _descriptor.Descriptor(
  name='DetectPersonsRequest',
  full_name='vrs.rpc.DetectPersonsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='VideoID', full_name='vrs.rpc.DetectPersonsRequest.VideoID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=281,
)


_SEARCHREQUEST = _descriptor.Descriptor(
  name='SearchRequest',
  full_name='vrs.rpc.SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ImgPath', full_name='vrs.rpc.SearchRequest.ImgPath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=315,
)


_SEARCHRESULT = _descriptor.Descriptor(
  name='SearchResult',
  full_name='vrs.rpc.SearchResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Score', full_name='vrs.rpc.SearchResult.Score', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FrameID', full_name='vrs.rpc.SearchResult.FrameID', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=363,
)


_PROCESSVIDEOREQUEST = _descriptor.Descriptor(
  name='ProcessVideoRequest',
  full_name='vrs.rpc.ProcessVideoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='VideoID', full_name='vrs.rpc.ProcessVideoRequest.VideoID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=403,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='vrs.rpc.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Code', full_name='vrs.rpc.Result.Code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Msg', full_name='vrs.rpc.Result.Msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=440,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='vrs.rpc.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=449,
)


_DETECTPERSONINIMGRESULT = _descriptor.Descriptor(
  name='DetectPersonInImgResult',
  full_name='vrs.rpc.DetectPersonInImgResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PersonID', full_name='vrs.rpc.DetectPersonInImgResult.PersonID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Top', full_name='vrs.rpc.DetectPersonInImgResult.Top', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Right', full_name='vrs.rpc.DetectPersonInImgResult.Right', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Bottom', full_name='vrs.rpc.DetectPersonInImgResult.Bottom', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Left', full_name='vrs.rpc.DetectPersonInImgResult.Left', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=552,
)

DESCRIPTOR.message_types_by_name['DetectObjectInImgRequest'] = _DETECTOBJECTINIMGREQUEST
DESCRIPTOR.message_types_by_name['DetectObjectInImgResult'] = _DETECTOBJECTINIMGRESULT
DESCRIPTOR.message_types_by_name['DetectPersonInImgRequest'] = _DETECTPERSONINIMGREQUEST
DESCRIPTOR.message_types_by_name['DetectPersonsRequest'] = _DETECTPERSONSREQUEST
DESCRIPTOR.message_types_by_name['SearchRequest'] = _SEARCHREQUEST
DESCRIPTOR.message_types_by_name['SearchResult'] = _SEARCHRESULT
DESCRIPTOR.message_types_by_name['ProcessVideoRequest'] = _PROCESSVIDEOREQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['DetectPersonInImgResult'] = _DETECTPERSONINIMGRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DetectObjectInImgRequest = _reflection.GeneratedProtocolMessageType('DetectObjectInImgRequest', (_message.Message,), dict(
  DESCRIPTOR = _DETECTOBJECTINIMGREQUEST,
  __module__ = 'vrs_pb2'
  # @@protoc_insertion_point(class_scope:vrs.rpc.DetectObjectInImgRequest)
  ))
_sym_db.RegisterMessage(DetectObjectInImgRequest)

DetectObjectInImgResult = _reflection.GeneratedProtocolMessageType('DetectObjectInImgResult', (_message.Message,), dict(
  DESCRIPTOR = _DETECTOBJECTINIMGRESULT,
  __module__ = 'vrs_pb2'
  # @@protoc_insertion_point(class_scope:vrs.rpc.DetectObjectInImgResult)
  ))
_sym_db.RegisterMessage(DetectObjectInImgResult)

DetectPersonInImgRequest = _reflection.GeneratedProtocolMessageType('DetectPersonInImgRequest', (_message.Message,), dict(
  DESCRIPTOR = _DETECTPERSONINIMGREQUEST,
  __module__ = 'vrs_pb2'
  # @@protoc_insertion_point(class_scope:vrs.rpc.DetectPersonInImgRequest)
  ))
_sym_db.RegisterMessage(DetectPersonInImgRequest)

DetectPersonsRequest = _reflection.GeneratedProtocolMessageType('DetectPersonsRequest', (_message.Message,), dict(
  DESCRIPTOR = _DETECTPERSONSREQUEST,
  __module__ = 'vrs_pb2'
  # @@protoc_insertion_point(class_scope:vrs.rpc.DetectPersonsRequest)
  ))
_sym_db.RegisterMessage(DetectPersonsRequest)

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHREQUEST,
  __module__ = 'vrs_pb2'
  # @@protoc_insertion_point(class_scope:vrs.rpc.SearchRequest)
  ))
_sym_db.RegisterMessage(SearchRequest)

SearchResult = _reflection.GeneratedProtocolMessageType('SearchResult', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHRESULT,
  __module__ = 'vrs_pb2'
  # @@protoc_insertion_point(class_scope:vrs.rpc.SearchResult)
  ))
_sym_db.RegisterMessage(SearchResult)

ProcessVideoRequest = _reflection.GeneratedProtocolMessageType('ProcessVideoRequest', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSVIDEOREQUEST,
  __module__ = 'vrs_pb2'
  # @@protoc_insertion_point(class_scope:vrs.rpc.ProcessVideoRequest)
  ))
_sym_db.RegisterMessage(ProcessVideoRequest)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'vrs_pb2'
  # @@protoc_insertion_point(class_scope:vrs.rpc.Result)
  ))
_sym_db.RegisterMessage(Result)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'vrs_pb2'
  # @@protoc_insertion_point(class_scope:vrs.rpc.Empty)
  ))
_sym_db.RegisterMessage(Empty)

DetectPersonInImgResult = _reflection.GeneratedProtocolMessageType('DetectPersonInImgResult', (_message.Message,), dict(
  DESCRIPTOR = _DETECTPERSONINIMGRESULT,
  __module__ = 'vrs_pb2'
  # @@protoc_insertion_point(class_scope:vrs.rpc.DetectPersonInImgResult)
  ))
_sym_db.RegisterMessage(DetectPersonInImgResult)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025edu.gcu.vrs.rpcserverP\001'))

_VRSRPC = _descriptor.ServiceDescriptor(
  name='VrsRpc',
  full_name='vrs.rpc.VrsRpc',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=555,
  serialized_end=733,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='vrs.rpc.VrsRpc.Search',
    index=0,
    containing_service=None,
    input_type=_SEARCHREQUEST,
    output_type=_SEARCHRESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ProcessVideo',
    full_name='vrs.rpc.VrsRpc.ProcessVideo',
    index=1,
    containing_service=None,
    input_type=_PROCESSVIDEOREQUEST,
    output_type=_RESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Merge',
    full_name='vrs.rpc.VrsRpc.Merge',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VRSRPC)

DESCRIPTOR.services_by_name['VrsRpc'] = _VRSRPC


_FACERPC = _descriptor.ServiceDescriptor(
  name='FaceRpc',
  full_name='vrs.rpc.FaceRpc',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=736,
  serialized_end=966,
  methods=[
  _descriptor.MethodDescriptor(
    name='BuildClassifer',
    full_name='vrs.rpc.FaceRpc.BuildClassifer',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DetectPersonsInVideo',
    full_name='vrs.rpc.FaceRpc.DetectPersonsInVideo',
    index=1,
    containing_service=None,
    input_type=_DETECTPERSONSREQUEST,
    output_type=_RESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DetectPersonInImg',
    full_name='vrs.rpc.FaceRpc.DetectPersonInImg',
    index=2,
    containing_service=None,
    input_type=_DETECTPERSONINIMGREQUEST,
    output_type=_DETECTPERSONINIMGRESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACERPC)

DESCRIPTOR.services_by_name['FaceRpc'] = _FACERPC


_OBJECTRPC = _descriptor.ServiceDescriptor(
  name='ObjectRpc',
  full_name='vrs.rpc.ObjectRpc',
  file=DESCRIPTOR,
  index=2,
  options=None,
  serialized_start=968,
  serialized_end=1073,
  methods=[
  _descriptor.MethodDescriptor(
    name='DetectObjectInImg',
    full_name='vrs.rpc.ObjectRpc.DetectObjectInImg',
    index=0,
    containing_service=None,
    input_type=_DETECTOBJECTINIMGREQUEST,
    output_type=_DETECTOBJECTINIMGRESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OBJECTRPC)

DESCRIPTOR.services_by_name['ObjectRpc'] = _OBJECTRPC

# @@protoc_insertion_point(module_scope)
